#QOL CONFIG#

#sign editing QOL
#makes Editing signs possible
sign_editing: true

#trample protection QOL
#protects farmland from getting trampled
trample_protection: true

#easy harvest QOL
#harvest field plants by right-clicking
easy_harvest: true
